### ISSUE TITLE
WAService.js:4 Uncaught Error: module "redux.js" is not defined

### ISSUE THREAD

**Issue by yi** [xixilive/redux-weapp#1]
The `require` mechanism in weapp seems to be different from commonjs. 
What is the proper way to setup redux for weapp?

**Comment by yi** [comment]
找到您的文章了，谢谢 问题解决了。
http://www.ifanr.com/minapp/790017

**Comment by xixilive** [comment]
👍

**Comment by yi** [comment]
用了一下，我觉得你这个主意很棒。相当于把微信的框架当做渲染层用，主要的程序逻辑在自己的es6里面用 redux 来驱动。这样做出来的产品体验可以细腻很多。 

但是现在有一个问题。就是随着项目实现代码的生长，myapp 的 module.export 会变得越来越复杂。 虽然这不是一个严重的问题，但是还是会越来越不方便。 

有什么更好的办法吗？

**Comment by xixilive** [comment]
weapp打包尺寸限1M, 没办法太复杂 😄

**Comment by yi** [comment]
不完全是这样。
1M 足够了，可以做很多很多事情。
