### ISSUE TITLE
onStateChange 事件处理方法中如何得到当前的 state?

### ISSUE THREAD

**Issue by yi** [xixilive/redux-weapp#2]
需要手动维持当前的 state吗？还是已经有现成的办法了？

```
onStateChange(nextState){
    // I want to compare current state with incoming new state.
 }
```

谢谢

**Comment by xixilive** [comment]
store变化时, **会使用connect时制定的mapState函数提取你所关注的store state**, 然后进行shallowEqual比较, 有差异时, 会自动调用一次onStateChange callback. 



https://github.com/xixilive/redux-weapp/blob/master/es6/connect.js#L6
