### ISSUE TITLE
weapp 的 template 如何自我管理状态，有什么好办法吗？

### ISSUE THREAD

**Issue by yi** [xixilive/redux-weapp#4]
weapp 的 template 如何自我管理状态，有什么好办法吗？

weapp 的 template 是一个单纯的渲染处理器。那么要实现根据用户交互的多级状态的组件，就比较麻烦了，因为组件的状态跟组件的渲染完全分离了。

对这样的情况，您有啥绝妙的主意吗？

方便留个微信或者QQ聊么？

我的微信 : good-day

**Comment by xixilive** [comment]
Pub/Sub? 我只会这个唉 😢
